/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class givtech_ebdcrypto_GenerateCertCSR */

#ifndef _Included_givtech_ebdcrypto_GenerateCertCSR
#define _Included_givtech_ebdcrypto_GenerateCertCSR
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     givtech_ebdcrypto_GenerateCertCSR
 * Method:    nativeGenPubCSR
 * Signature: ([BII[BII[BII[BII[BII[BII[BII[BII)[B
 */
JNIEXPORT jbyteArray JNICALL Java_givtech_ebdcrypto_GenerateCertCSR_nativeGenPubCSR
  (JNIEnv *, jobject, jbyteArray, jint, jint, jbyteArray, jint, jint, jbyteArray, jint, jint, jbyteArray, jint, jint, jbyteArray, jint, jint, jbyteArray, jint, jint, jbyteArray, jint, jint, jbyteArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
