/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class givtech_ebdcrypto */

#ifndef _Included_givtech_ebdcrypto
#define _Included_givtech_ebdcrypto
#ifdef __cplusplus
extern "C" {
#endif
#undef givtech_ebdcrypto_AES_AES_BLOCK_SIZE
#define givtech_ebdcrypto_AES_AES_BLOCK_SIZE 16L
#undef givtech_ebdcrypto_AES_AES128
#define givtech_ebdcrypto_AES_AES128 16L
#undef givtech_ebdcrypto_AES_AES192
#define givtech_ebdcrypto_AES_AES192 24L
#undef givtech_ebdcrypto_AES_AES256
#define givtech_ebdcrypto_AES_AES256 32L
#undef givtech_ebdcrypto_AES_ENCRYPT
#define givtech_ebdcrypto_AES_ENCRYPT 1L
#undef givtech_ebdcrypto_AES_DECRYPT
#define givtech_ebdcrypto_AES_DECRYPT 0L
/*
 * Class:     givtech_ebdcrypto_AES
 * Method:    nativeAESCBC
 * Signature: (I[BI[B[BI[B)I
 */
JNIEXPORT jint JNICALL Java_givtech_ebdcrypto_AES_nativeAESCBC (JNIEnv *, jobject, jint, jbyteArray, jint, jint, jbyteArray, jint, jbyteArray, jint, jint, jbyteArray, jint);



#undef givtech_ebdcrypto_SHA2_SHA224
#define givtech_ebdcrypto_SHA2_SHA224 33L
#undef givtech_ebdcrypto_SHA2_SHA256
#define givtech_ebdcrypto_SHA2_SHA256 34L
#undef givtech_ebdcrypto_SHA2_SHA384
#define givtech_ebdcrypto_SHA2_SHA384 35L
#undef givtech_ebdcrypto_SHA2_SHA512
#define givtech_ebdcrypto_SHA2_SHA512 36L
#undef givtech_ebdcrypto_SHA2_SHA224_DIGEST_LENGTH
#define givtech_ebdcrypto_SHA2_SHA224_DIGEST_LENGTH 24L
#undef givtech_ebdcrypto_SHA2_SHA256_DIGEST_LENGTH
#define givtech_ebdcrypto_SHA2_SHA256_DIGEST_LENGTH 32L
#undef givtech_ebdcrypto_SHA2_SHA384_DIGEST_LENGTH
#define givtech_ebdcrypto_SHA2_SHA384_DIGEST_LENGTH 48L
#undef givtech_ebdcrypto_SHA2_SHA512_DIGEST_LENGTH
#define givtech_ebdcrypto_SHA2_SHA512_DIGEST_LENGTH 64L
/*
 * Class:     givtech_ebdcrypto_SHA2
 * Method:    nativesha224
 * Signature: ([BI[B)I
 */
JNIEXPORT jint JNICALL Java_givtech_ebdcrypto_SHA2_nativesha224 (JNIEnv *, jobject, jbyteArray, jint, jint, jbyteArray, jint);

/*
 * Class:     givtech_ebdcrypto_SHA2
 * Method:    nativesha256
 * Signature: ([BI[B)I
 */
JNIEXPORT jint JNICALL Java_givtech_ebdcrypto_SHA2_nativesha256 (JNIEnv *, jobject, jbyteArray, jint, jint, jbyteArray, jint);

/*
 * Class:     givtech_ebdcrypto_SHA2
 * Method:    nativesha384
 * Signature: ([BI[B)I
 */
JNIEXPORT jint JNICALL Java_givtech_ebdcrypto_SHA2_nativesha384 (JNIEnv *, jobject, jbyteArray, jint, jint, jbyteArray, jint);

/*
 * Class:     givtech_ebdcrypto_SHA2
 * Method:    nativesha512
 * Signature: ([BI[B)I
 */
JNIEXPORT jint JNICALL Java_givtech_ebdcrypto_SHA2_nativesha512 (JNIEnv *, jobject, jbyteArray, jint, jint, jbyteArray, jint);



/*
 * Class:     givtech_ebdcrypto_DRBG
 * Method:    nativeDRBGRandomGen
 * Signature: ([BII)I
 */
JNIEXPORT jint JNICALL Java_givtech_ebdcrypto_DRBG_nativeDRBGRandomGen (JNIEnv *, jobject, jbyteArray, jint, jint);



#undef givtech_ebdcrypto_ECDSA_SIGN
#define givtech_ebdcrypto_ECDSA_SIGN 1L
#undef givtech_ebdcrypto_ECDSA_VERIFY
#define givtech_ebdcrypto_ECDSA_VERIFY 0L
#undef givtech_ebdcrypto_ECDSA_SHA224
#define givtech_ebdcrypto_ECDSA_SHA224 33L
#undef givtech_ebdcrypto_ECDSA_SHA256
#define givtech_ebdcrypto_ECDSA_SHA256 34L
#undef givtech_ebdcrypto_ECDSA_SHA384
#define givtech_ebdcrypto_ECDSA_SHA384 35L
#undef givtech_ebdcrypto_ECDSA_SHA512
#define givtech_ebdcrypto_ECDSA_SHA512 36L
/*
 * Class:     givtech_ebdcrypto_ECDSA
 * Method:    nativeECDSAgenkeypair
 * Signature: ([BI[I[BI[I[BI[I)I
 */
JNIEXPORT jint JNICALL Java_givtech_ebdcrypto_ECDSA_nativeECDSAgenkeypair (JNIEnv *, jobject, jbyteArray, jint, jintArray, jbyteArray, jint, jintArray, jbyteArray, jint, jintArray);

/*
 * Class:     givtech_ebdcrypto_ECDSA
 * Method:    nativeECDSAgeneratesignature
 * Signature: (I[BII[BII[BI[I[BI[I)I
 */
JNIEXPORT jint JNICALL Java_givtech_ebdcrypto_ECDSA_nativeECDSAgeneratesignature (JNIEnv *, jobject, jint, jbyteArray, jint, jint, jbyteArray, jint, jint, jbyteArray, jint, jintArray, jbyteArray, jint, jintArray);

/*
 * Class:     givtech_ebdcrypto_ECDSA
 * Method:    nativeECDSAverifysignature
 * Signature: (I[BII[BII[BII[BII[BII)I
 */
JNIEXPORT jint JNICALL Java_givtech_ebdcrypto_ECDSA_nativeECDSAverifysignature (JNIEnv *, jobject, jint, jbyteArray, jint, jint, jbyteArray, jint, jint, jbyteArray, jint, jint, jbyteArray, jint, jint, jbyteArray, jint, jint);

/*
 * Class:     givtech_ebdcrypto_GenerateCertCSR
 * Method:    nativeGenPubCSR
 * Signature: ([BII[BII[BII[BII[BII[BII[BII[BII)[B
 */
JNIEXPORT jbyteArray JNICALL Java_givtech_ebdcrypto_GenerateCertCSR_nativeGenPubCSR
        (JNIEnv *, jobject, jbyteArray, jint, jint, jbyteArray, jint, jint, jbyteArray, jint, jint, jbyteArray, jint, jint, jbyteArray, jint, jint, jbyteArray, jint, jint, jbyteArray, jint, jint, jbyteArray, jint, jint);


#ifdef __cplusplus
}
#endif
#endif
